//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFloricola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLOQUES_VARIEDADES
    {
        public int BLVCODIGOI { get; set; }
        public int BLQCODIGOI { get; set; }
        public int VRDCODIGOI { get; set; }
        public Nullable<int> BLVNUMEROCAMA { get; set; }
        public Nullable<int> BLVCANTIDAD { get; set; }
        public string BLVOBSERVACION { get; set; }
        public System.DateTime BLVFECHA { get; set; }
    
        public virtual BLOQUES BLOQUES { get; set; }
        public virtual VARIEDADES VARIEDADES { get; set; }
    }
}
