//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFloricola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTES()
        {
            this.PREENVIOS = new HashSet<PREENVIOS>();
        }
    
        public int CLNCODIGOI { get; set; }
        public int ESTCODIGOI { get; set; }
        public string CLNRUC { get; set; }
        public string CLNRAZONSOCIAL { get; set; }
        public string CLNDIRECCION { get; set; }
        public string CLNCONSIGNATARIO { get; set; }
        public string CLNTELEFONO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PREENVIOS> PREENVIOS { get; set; }
        public virtual ESTADOS ESTADOS { get; set; }
    }
}
