//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFloricola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONCILIACION
    {
        public int CNCCODIGOI { get; set; }
        public Nullable<int> PRECODIGOI { get; set; }
        public Nullable<System.DateTime> CNCFECHA { get; set; }
        public Nullable<bool> CNCESTADO { get; set; }
        public string CNCOBSERVACION { get; set; }
    
        public virtual PREENVIOS PREENVIOS { get; set; }
    }
}
