//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFloricola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTROLES_FLOR_NACIONAL
    {
        public int CFNCODIGOI { get; set; }
        public int TPCCODIGOI { get; set; }
        public int PRCCODIGOI { get; set; }
        public Nullable<int> VRDCODIGOI { get; set; }
        public int CFNCANTIDAD { get; set; }
        public string CFNOBSERVACION { get; set; }
    
        public virtual TIPO_CAUSAS TIPO_CAUSAS { get; set; }
        public virtual VARIEDADES VARIEDADES { get; set; }
        public virtual PROCESO_CLASIFICACION PROCESO_CLASIFICACION { get; set; }
    }
}
