//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFloricola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLES_PREENVIOS
    {
        public int DTPCODIGOI { get; set; }
        public int DTECODIGOI { get; set; }
        public int PRECODIGOI { get; set; }
        public int DTPCANTIDAD { get; set; }
    
        public virtual DETALLE_FLOR_CLASIFICADA DETALLE_FLOR_CLASIFICADA { get; set; }
        public virtual PREENVIOS PREENVIOS { get; set; }
    }
}
