//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFloricola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_FLOR_CLASIFICADA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DETALLE_FLOR_CLASIFICADA()
        {
            this.DETALLES_PREENVIOS = new HashSet<DETALLES_PREENVIOS>();
        }
    
        public int DTECODIGOI { get; set; }
        public int TMTCODIGOI { get; set; }
        public int UNDCODIGOI { get; set; }
        public int TPFCODIGOI { get; set; }
        public int PRCCODIGOI { get; set; }
        public int VRDCODIGOI { get; set; }
        public System.DateTime DTEFECHAINGRESO { get; set; }
        public int DTECANTIDAD { get; set; }
        public string DTEOBSERVACION { get; set; }
    
        public virtual PROCESO_CLASIFICACION PROCESO_CLASIFICACION { get; set; }
        public virtual TAMANO_TALLOS TAMANO_TALLOS { get; set; }
        public virtual TIPOS_FLORES TIPOS_FLORES { get; set; }
        public virtual UNIDADES UNIDADES { get; set; }
        public virtual VARIEDADES VARIEDADES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLES_PREENVIOS> DETALLES_PREENVIOS { get; set; }
    }
}
