//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFloricola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLEADOS()
        {
            this.USUARIOS = new HashSet<USUARIOS>();
        }
    
        public int EPLCODIGOI { get; set; }
        public int EMPCODIGOI { get; set; }
        public string EPLCEDULA { get; set; }
        public string EPLAPELLIDOP { get; set; }
        public string EPLAPELLIDOM { get; set; }
        public string EPLNOMBRES { get; set; }
        public string EPLDIRECCION { get; set; }
        public string EPLTELEFONO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIOS> USUARIOS { get; set; }
        public virtual EMPRESAS EMPRESAS { get; set; }
    }
}
