//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFloricola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INGRESO_PRODUCCION
    {
        public int INPCODIGOI { get; set; }
        public int BLCCODIGOI { get; set; }
        public Nullable<int> VRDCODIGOI { get; set; }
        public int CNPCODIGOI { get; set; }
        public int INPNUMMALLAS { get; set; }
        public Nullable<System.DateTime> INPFECHA { get; set; }
        public int INPCANTIDADTALLOS { get; set; }
    
        public virtual BLOQUES BLOQUES { get; set; }
        public virtual CONTROL_PRODUCCION CONTROL_PRODUCCION { get; set; }
        public virtual VARIEDADES VARIEDADES { get; set; }
    }
}
