//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFloricola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREENVIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PREENVIOS()
        {
            this.CONCILIACION = new HashSet<CONCILIACION>();
            this.DETALLES_PREENVIOS = new HashSet<DETALLES_PREENVIOS>();
        }
    
        public int PRECODIGOI { get; set; }
        public int CLNCODIGOI { get; set; }
        public System.DateTime PREFECHA { get; set; }
        public decimal PRENUMERO { get; set; }
        public string PREAWB { get; set; }
        public string PREHAWB { get; set; }
        public int PRENUMPIEZAS { get; set; }
        public string PREIDCAJAS { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONCILIACION> CONCILIACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLES_PREENVIOS> DETALLES_PREENVIOS { get; set; }
    }
}
