//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFloricola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_CAUSAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_CAUSAS()
        {
            this.CONTROLES_FLOR_NACIONAL = new HashSet<CONTROLES_FLOR_NACIONAL>();
        }
    
        public int TPCCODIGOI { get; set; }
        public int CAUCODIGOI { get; set; }
        public string TPCDESCRIPCION { get; set; }
        public bool TPCESTADO { get; set; }
    
        public virtual CAUSAS CAUSAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTROLES_FLOR_NACIONAL> CONTROLES_FLOR_NACIONAL { get; set; }
    }
}
